/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 robot.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("models/robot.gltf");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Robot_Arm_Base_2_Isai_node.geometry}
        material={materials.Mat_1}
      />
      <mesh
        geometry={nodes.Arm2_Isai_node.geometry}
        material={materials.Mat_1}
      />
      <mesh
        geometry={nodes.Cylinder_Base_Isai_node.geometry}
        material={materials.Mat_1}
      />
      <mesh geometry={nodes.nodes6.geometry} material={materials.Mat_4} />
      <mesh geometry={nodes.nodes7.geometry} material={materials.Mat_4} />
      <mesh geometry={nodes.nodes8.geometry} material={materials.Mat_4} />
      <mesh geometry={nodes.nodes9.geometry} material={materials.Mat_4} />
      <mesh geometry={nodes.nodes10.geometry} material={materials.Mat_4} />
      <mesh geometry={nodes.nodes11.geometry} material={materials.Mat_4} />
      <mesh geometry={nodes.nodes12.geometry} material={materials.Mat_4} />
      <mesh geometry={nodes.nodes13.geometry} material={materials.Mat_4} />
      <mesh geometry={nodes.nodes14.geometry} material={materials.Mat_4} />
      <mesh
        geometry={nodes.Arm1_Isai_20_node.geometry}
        material={materials.Mat_1}
      />
    </group>
  );
}

useGLTF.preload("models/robot.gltf");
